# worker_service/template.yaml (Required Infrastructure as Code File)

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Asynchronous Worker Lambda for Model Scoring

Parameters:
  ImageUriParameter:
    Type: String
    Description: URI of the Docker image pushed to ECR.
  DynamoDBTableName:
    Type: String
  S3ArtifactBucketName:
    Type: String

Resources:
  # 1. The SQS Queue to trigger the worker
  ScoringQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 1800 # 30 minutes for long scoring jobs

  # 2. The Worker Lambda Function (Deployed from ECR Image)
  WorkerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image # Tell SAM to use a container image
      ImageUri: !Ref ImageUriParameter # Reference the URI passed from GitHub Actions
      Timeout: 1800 # 30 minutes max execution time
      MemorySize: 4096 # Allocate more memory for model scoring
      Policies:
        # Grants permissions to read the SQS queue
        - SQSPollerPolicy: !Ref ScoringQueue
        # Grants permissions to read the model sources from S3
        - S3ReadPolicy:
            BucketName: !Ref S3ArtifactBucketName
        # Grants permissions to update the DynamoDB table (the final link!)
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTableName
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          S3_ARTIFACT_BUCKET: !Ref S3ArtifactBucketName
      Events:
        ScoringQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScoringQueue.Arn
            BatchSize: 1 # Process one job at a time